### DISCUSSION TITLE
mac配合clash的使用方法

### DISCUSSION THREAD

**Discussion by liumingye** [1715173329/UnblockNeteaseMusic#1033] [General]
1. 首先安装证书 [安裝 UNM 的 HTTPS 憑證](https://github.com/UnblockNeteaseMusic/server/discussions/426)
2. 打开cfw，编辑Parsers
![截屏2023-03-23 21 16 13](https://user-images.githubusercontent.com/8676207/227216000-61437601-8c80-401a-8535-4f947af1efd6.png)
3. 粘贴配置并修改server和port为你自己的服务器，我这里使用的是docker
```parsers: # array
  - reg: (.*?)
    yaml:
      prepend-proxies:
        - name: UnblockNeteaseMusic_Local
          type: http
          server: localhost
          port: 7080
      prepend-proxy-groups:
        - name: UnblockNeteaseMusic
          type: select
          proxies:
            - UnblockNeteaseMusic_Local
      prepend-rules:
        - PROCESS-NAME,NeteaseMusic,UnblockNeteaseMusic
```

![截屏2023-03-23 21 20 39](https://user-images.githubusercontent.com/8676207/227217209-3d76b686-457c-4658-94a9-309590f4ff01.png)
4. 更新配置文件
![截屏2023-03-23 21 22 26](https://user-images.githubusercontent.com/8676207/227217407-1de32c32-4aa2-4100-adae-42c85b2aece5.png)

**Comment by liumingye** [comment]
本地配置文件 配置方法
```
proxies:
  .........
  - name: UnblockNeteaseMusic_Local
    type: http
    server: localhost
    port: 7080

proxy-groups:
  .........
  - name: UnblockNeteaseMusic
    type: select
    proxies:
      - UnblockNeteaseMusic_Local

rules:
  - PROCESS-NAME,NeteaseMusic,UnblockNeteaseMusic
  .........
```
