### ISSUE TITLE
Docker需更新

### ISSUE THREAD

**Issue by caizefeng** [1715173329/UnblockNeteaseMusic#230]
不论`docker pull pan93412/unblock-netease-music-enhanced`还是自己从Dockerfile build，都报错
`Please check the availability of match sources.`

**Comment by pan93412** [comment]
@1715173329 有可能是最新的依賴出問題了。幫我確認一下。

**Comment by pan93412** [comment]
> ENTRYPOINT ["sh", "-c", "node app.js -o $SOURCE \"$0\" \"$@\""]
> 
> 最终会变成 sh -c node app.js -o $SOURCE "" ""，多了后面两个双引号，所以报 "Please check the availability of match sources"
> 
> 应该把 $0 $@ 参数去掉，使用docker的command代替

@1715173329 patch it thx

**Comment by pan93412** [comment]
> > > ENTRYPOINT ["sh", "-c", "node app.js -o $SOURCE "$0" "$@""]
> > > 最终会变成 sh -c node app.js -o $SOURCE "" ""，多了后面两个双引号，所以报 "Please check the availability of match sources"
> > > 应该把 $0 $@ 参数去掉，使用docker的command代替
> > 
> > @1715173329 patch it thx
> 
> @alexchanchan @pan93412 我想，这里的话，大概直接去掉引号就可以了。

https://docs.docker.com/engine/reference/builder/

改成 CMD 不太適合我們的場景。

**Comment by FirstJavaMaster** [comment]
> > > > > ENTRYPOINT ["sh", "-c", "node app.js -o $SOURCE "$0" "$@""]
> > > > > 最终会变成 sh -c node app.js -o $SOURCE "" ""，多了后面两个双引号，所以报 "Please check the availability of match sources"
> > > > > 应该把 $0 $@ 参数去掉，使用docker的command代替
> > > > 
> > > > 
> > > > @1715173329 patch it thx
> > > 
> > > 
> > > @alexchanchan @pan93412 我想，这里的话，大概直接去掉引号就可以了。
> > 
> > 
> > https://docs.docker.com/engine/reference/builder/
> > 改成 CMD 不太適合我們的場景。
> 
> @pan93412 您误会了，我的意思是如果使用者想加自定义参数，自行添加参数在command，docker就会把command追加到entrypoint命令的后面了，Dockerfile不需要加CMD。 `docker run [OPTIONS] IMAGE[:TAG] [COMMAND]`


这是#201 的修改留下的后遗症, dockerfile确实不应该用这种方式预留参数位给调用者, 如果调用者没有传参数就会报错. 调用者可以用其他方式制定参数. 比如上面说的这种. 或者像我一样, 直接docker-compose重写:

```
version: '3'

services:
  unblockneteasemusic:
    image: pan93412/unblock-netease-music-enhanced
    restart: always
    ports:
      - 9999:8080
    entrypoint:
      - sh
      - -c
      - node app.js -o bilibili kugou kuwo -s -e http://music.163.com
```
